name: jarambahtv
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  event_bus: ^2.0.0
  file_picker: ^3.0.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^0.12.1+1
  provider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_tags: ^0.4.9+1
  get_it: ^6.0.0
  numberpicker: ^2.0.0
  shared_preferences: ^2.0.3
  unicorndial: ^1.1.5
  uuid: ^3.0.1



  dart_chromecast:
    git:
      url: https://github.com/fastogt/dart_chromecast.git
      ref: master
  fastotv_dart:
    git:
      url: https://gitlab.com/fastogt/fastotv_dart.git
      ref: master
  fastotv_device_info:
    git:
      url: https://gitlab.com/fastogt/fastotv_device_info.git
      ref: master
  flutter_fastotv_common:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_common.git
      ref: master
  player:
    git:
      url: https://gitlab.com/fastogt/flutter_fastotv_player.git
      ref: main

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - install/assets/
    - install/lang/
